# Site settings
title: Gary’s Economics Frequently Asked Questions
description: > # this means to ignore newlines until "baseurl:"
  A Frequently Asked Questions (FAQ) page, made by the community around the youtu.be/@garyseconomics channel
baseurl: "/faq" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
